version: '3.6'
services:
  puppy-back:
    image: node:latest
    depends_on:
      - puppy-db
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: ./node_modules/nodemon/bin/nodemon.js index.js
  puppy-db:
    image: mongo:latest
    ports:
      - "27017:27017"
